-- SkillForge PostgreSQL schema for Neon.
-- Run this file first, then run database/seed-neon.sql.

CREATE TABLE IF NOT EXISTS skillforge_users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    profile_image VARCHAR(255) DEFAULT 'default-avatar.png',
    bio TEXT,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skillforge_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    icon VARCHAR(50) DEFAULT 'briefcase',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skillforge_skills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    category_id INTEGER NOT NULL REFERENCES skillforge_categories(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skillforge_user_skills (
    user_id INTEGER NOT NULL REFERENCES skillforge_users(id) ON DELETE CASCADE,
    skill_id INTEGER NOT NULL REFERENCES skillforge_skills(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, skill_id)
);

CREATE TABLE IF NOT EXISTS skillforge_services (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    freelancer_id INTEGER NOT NULL REFERENCES skillforge_users(id) ON DELETE CASCADE,
    category_id INTEGER NOT NULL REFERENCES skillforge_categories(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    delivery_days INTEGER NOT NULL,
    rating DECIMAL(3,2) DEFAULT 0.00,
    review_count INTEGER DEFAULT 0,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skillforge_orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NOT NULL REFERENCES skillforge_users(id) ON DELETE CASCADE,
    freelancer_id INTEGER NOT NULL REFERENCES skillforge_users(id) ON DELETE CASCADE,
    service_id INTEGER NOT NULL REFERENCES skillforge_services(id) ON DELETE CASCADE,
    amount DECIMAL(10,2) NOT NULL,
    status VARCHAR(30) DEFAULT 'PENDING',
    requirements TEXT,
    delivery_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS skillforge_payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES skillforge_orders(id) ON DELETE CASCADE,
    amount DECIMAL(10,2) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    transaction_id VARCHAR(100) NOT NULL UNIQUE,
    status VARCHAR(30) DEFAULT 'COMPLETED',
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skillforge_reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES skillforge_orders(id) ON DELETE CASCADE,
    client_id INTEGER NOT NULL REFERENCES skillforge_users(id) ON DELETE CASCADE,
    freelancer_id INTEGER NOT NULL REFERENCES skillforge_users(id) ON DELETE CASCADE,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skillforge_wishlist (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NOT NULL REFERENCES skillforge_users(id) ON DELETE CASCADE,
    service_id INTEGER NOT NULL REFERENCES skillforge_services(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_skillforge_wishlist_client_service UNIQUE (client_id, service_id)
);

CREATE INDEX IF NOT EXISTS idx_skillforge_users_role ON skillforge_users(role);
CREATE INDEX IF NOT EXISTS idx_skillforge_users_username ON skillforge_users(username);
CREATE INDEX IF NOT EXISTS idx_skillforge_users_email ON skillforge_users(email);
CREATE INDEX IF NOT EXISTS idx_skillforge_skills_category ON skillforge_skills(category_id);
CREATE INDEX IF NOT EXISTS idx_skillforge_services_category ON skillforge_services(category_id);
CREATE INDEX IF NOT EXISTS idx_skillforge_services_freelancer ON skillforge_services(freelancer_id);
CREATE INDEX IF NOT EXISTS idx_skillforge_services_status ON skillforge_services(status);
CREATE INDEX IF NOT EXISTS idx_skillforge_orders_client ON skillforge_orders(client_id);
CREATE INDEX IF NOT EXISTS idx_skillforge_orders_freelancer ON skillforge_orders(freelancer_id);
CREATE INDEX IF NOT EXISTS idx_skillforge_orders_status ON skillforge_orders(status);
CREATE INDEX IF NOT EXISTS idx_skillforge_payments_order ON skillforge_payments(order_id);
CREATE INDEX IF NOT EXISTS idx_skillforge_reviews_freelancer ON skillforge_reviews(freelancer_id);
CREATE INDEX IF NOT EXISTS idx_skillforge_reviews_order ON skillforge_reviews(order_id);
